kumuluzee:
  name: new-world-game
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8080
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        jndi-name: jdbc/mainDB
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:postgresql://localhost:5432/new-world
      username: postgres
      password: postgres
      max-pool-size: 20
  security:
    disable-jetty-auth: true
    keycloak:
      json: '{
              "realm": "new-world",
              "bearer-only": true,
              "auth-server-url": "https://keycloak.mjamsek.com/auth",
              "ssl-required": "external",
              "resource": "game-service"
            }'

game-service:
  logging:
    severity: DEBUG
